/********************************************************************************\
**                                                                              **
**  Copyright (C) 2008 Josh Ventura                                             **
**                                                                              **
**  This file is a part of the ENIGMA Development Environment.                  **
**                                                                              **
**                                                                              **
**  ENIGMA is free software: you can redistribute it and/or modify it under the **
**  terms of the GNU General Public License as published by the Free Software   **
**  Foundation, version 3 of the license or any later version.                  **
**                                                                              **
**  This application and its source code is distributed AS-IS, WITHOUT ANY      **
**  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS   **
**  FOR A PARTICULAR PURPOSE. See the GNU General Public License for more       **
**  details.                                                                    **
**                                                                              **
**  You should have recieved a copy of the GNU General Public License along     **
**  with this code. If not, see <http://www.gnu.org/licenses/>                  **
**                                                                              **
**  ENIGMA is an environment designed to create games and other programs with a **
**  high-level, fully compilable language. Developers of ENIGMA or anything     **
**  associated with ENIGMA are in no way responsible for its users or           **
**  applications created by its users, or damages caused by the environment     **
**  or programs made in the environment.                                        **
**                                                                              **
\********************************************************************************/

//This file was generated by the ENIGMA Development Environment.
//Editing it is a sign of a certain medical condition. We're not sure which one.

// Script arguments
variant argument0 = 0, argument1 = 0, argument2 = 0;


namespace enigma
{
  struct ENIGMA_global_structure: object_locals
  {
    var Y;
    var a0;
    var a1;
    var ammo;
    var b0;
    var b1;
    var center;
    var contrafont;
    var i;
    var other_hspeed;
    var other_x;
    var p1;
    var p2;
    var size1;
    var size2;
    var x1;
    var y1;
    ENIGMA_global_structure(const int x, const int y): object_locals(x,y) {}
  };
  object_basic *ENIGMA_global_instance = new ENIGMA_global_structure(global,global);
}
