/********************************************************************************\
**                                                                              **
**  Copyright (C) 2008 Josh Ventura                                             **
**                                                                              **
**  This file is a part of the ENIGMA Development Environment.                  **
**                                                                              **
**                                                                              **
**  ENIGMA is free software: you can redistribute it and/or modify it under the **
**  terms of the GNU General Public License as published by the Free Software   **
**  Foundation, version 3 of the license or any later version.                  **
**                                                                              **
**  This application and its source code is distributed AS-IS, WITHOUT ANY      **
**  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS   **
**  FOR A PARTICULAR PURPOSE. See the GNU General Public License for more       **
**  details.                                                                    **
**                                                                              **
**  You should have recieved a copy of the GNU General Public License along     **
**  with this code. If not, see <http://www.gnu.org/licenses/>                  **
**                                                                              **
**  ENIGMA is an environment designed to create games and other programs with a **
**  high-level, fully compilable language. Developers of ENIGMA or anything     **
**  associated with ENIGMA are in no way responsible for its users or           **
**  applications created by its users, or damages caused by the environment     **
**  or programs made in the environment.                                        **
**                                                                              **
\********************************************************************************/

//This file was generated by the ENIGMA Development Environment.
//Editing it is a sign of a certain medical condition. We're not sure which one.

case 0:
    new enigma::OBJ_tank(x,y,idn);
  break;
case 1:
    new enigma::OBJ_turret1(x,y,idn);
  break;
case 2:
    new enigma::OBJ_bullet(x,y,idn);
  break;
case 3:
    new enigma::OBJ_dest(x,y,idn);
  break;
case 4:
    new enigma::OBJ_cursor1(x,y,idn);
  break;
case 5:
    new enigma::OBJ_baddybullet(x,y,idn);
  break;
case 6:
    new enigma::OBJ_controller(x,y,idn);
  break;
case 8:
    new enigma::OBJ_enemy_tank(x,y,idn);
  break;
case 9:
    new enigma::OBJ_explosion(x,y,idn);
  break;
case 10:
    new enigma::OBJ_enemyturret(x,y,idn);
  break;
case 11:
    new enigma::OBJ_enemy_tank2(x,y,idn);
  break;
case 13:
    new enigma::OBJ_enemyturret2(x,y,idn);
  break;
case 14:
    new enigma::OBJ_missle_turrret(x,y,idn);
  break;
case 15:
    new enigma::OBJ_laser(x,y,idn);
  break;
case 16:
    new enigma::OBJ_missle(x,y,idn);
  break;
case 17:
    new enigma::OBJ_missle_turret(x,y,idn);
  break;
case 18:
    new enigma::OBJ_enigmaauto(x,y,idn);
  break;
case 19:
    new enigma::OBJ_bullet2(x,y,idn);
  break;
case 20:
    new enigma::OBJ_flag(x,y,idn);
  break;
case 21:
    new enigma::OBJ_baddybullet2(x,y,idn);
  break;
case 22:
    new enigma::OBJ_explo2(x,y,idn);
  break;
case 24:
    new enigma::OBJ_boomtu(x,y,idn);
  break;
case 25:
    new enigma::OBJ_boomlazer(x,y,idn);
  break;
case 26:
    new enigma::OBJ_dest2(x,y,idn);
  break;
case 27:
    new enigma::OBJ_enemyturret3(x,y,idn);
  break;
case 29:
    new enigma::OBJ_baddybullet3(x,y,idn);
  break;
case 30:
    new enigma::OBJ_baddybullet4(x,y,idn);
  break;
case 31:
    new enigma::OBJ_enemyturret4(x,y,idn);
  break;
case 33:
    new enigma::OBJ_obj_minimap(x,y,idn);
  break;
case 34:
    new enigma::OBJ_blocko(x,y,idn);
  break;
case 35:
    new enigma::OBJ_title(x,y,idn);
  break;
case 37:
    new enigma::OBJ_hangars(x,y,idn);
  break;
case 38:
    new enigma::OBJ_HQ(x,y,idn);
  break;
case 43:
    new enigma::OBJ_baseturret(x,y,idn);
  break;
case 44:
    new enigma::OBJ_baddybullet5(x,y,idn);
  break;
case 45:
    new enigma::OBJ_base(x,y,idn);
  break;
case 46:
    new enigma::OBJ_bulletv(x,y,idn);
  break;
case 51:
    new enigma::OBJ_someting(x,y,idn);
  break;
case 57:
    new enigma::OBJ_bullet4(x,y,idn);
  break;
case 63:
    new enigma::OBJ_flamb(x,y,idn);
  break;
case 64:
    new enigma::OBJ_explosionb(x,y,idn);
  break;
case 65:
    new enigma::OBJ_smoke(x,y,idn);
  break;
case 68:
    new enigma::OBJ_allie(x,y,idn);
  break;
case 69:
    new enigma::OBJ_allie_turret(x,y,idn);
  break;
case 70:
    new enigma::OBJ_alliedbullet(x,y,idn);
  break;
case 73:
    new enigma::OBJ_mmc1(x,y,idn);
  break;
case 79:
    new enigma::OBJ_activator1(x,y,idn);
  break;
case 83:
    new enigma::OBJ_messenger(x,y,idn);
  break;
case 87:
    new enigma::OBJ_tank1(x,y,idn);
  break;
case 88:
    new enigma::OBJ_turret2(x,y,idn);
  break;
case 89:
    new enigma::OBJ_controller2(x,y,idn);
  break;
case 91:
    new enigma::OBJ_bullet5(x,y,idn);
  break;
case 93:
    new enigma::OBJ_activator2(x,y,idn);
  break;
case 95:
    new enigma::OBJ_activator3(x,y,idn);
  break;
case 96:
    new enigma::OBJ_intro(x,y,idn);
  break;
case 97:
    new enigma::OBJ_enigmatm(x,y,idn);
  break;
case 98:
    new enigma::OBJ_tmm(x,y,idn);
  break;
case 99:
    new enigma::OBJ_NEW(x,y,idn);
  break;
case 100:
    new enigma::OBJ_LOAD(x,y,idn);
  break;
case 101:
    new enigma::OBJ_OPTION(x,y,idn);
  break;
case 102:
    new enigma::OBJ_dummy(x,y,idn);
  break;
case 103:
    new enigma::OBJ_dummyt(x,y,idn);
  break;
case 104:
    new enigma::OBJ_enemy_tankt1(x,y,idn);
  break;
case 105:
    new enigma::OBJ_enemyturrett1(x,y,idn);
  break;
case 106:
    new enigma::OBJ_baddybullet6(x,y,idn);
  break;
case 107:
    new enigma::OBJ_baset1(x,y,idn);
  break;
case 108:
    new enigma::OBJ_baseturrett1(x,y,idn);
  break;
case 109:
    new enigma::OBJ_baddybullet7(x,y,idn);
  break;
case 110:
    new enigma::OBJ_activator4(x,y,idn);
  break;
case 113:
    new enigma::OBJ_smallblock(x,y,idn);
  break;
case 114:
    new enigma::OBJ_biggerblock(x,y,idn);
  break;

