/********************************************************************************\
**                                                                              **
**  Copyright (C) 2008 Josh Ventura                                             **
**                                                                              **
**  This file is a part of the ENIGMA Development Environment.                  **
**                                                                              **
**                                                                              **
**  ENIGMA is free software: you can redistribute it and/or modify it under the **
**  terms of the GNU General Public License as published by the Free Software   **
**  Foundation, version 3 of the license or any later version.                  **
**                                                                              **
**  This application and its source code is distributed AS-IS, WITHOUT ANY      **
**  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS   **
**  FOR A PARTICULAR PURPOSE. See the GNU General Public License for more       **
**  details.                                                                    **
**                                                                              **
**  You should have recieved a copy of the GNU General Public License along     **
**  with this code. If not, see <http://www.gnu.org/licenses/>                  **
**                                                                              **
**  ENIGMA is an environment designed to create games and other programs with a **
**  high-level, fully compilable language. Developers of ENIGMA or anything     **
**  associated with ENIGMA are in no way responsible for its users or           **
**  applications created by its users, or damages caused by the environment     **
**  or programs made in the environment.                                        **
**                                                                              **
\********************************************************************************/

//This file was generated by the ENIGMA Development Environment.
//Editing it is a sign of a certain medical condition. We're not sure which one.

case 0:
    new enigma::OBJ_Block(x,y,idn);
  break;
case 1:
    new enigma::OBJ_Curve1(x,y,idn);
  break;
case 2:
    new enigma::OBJ_Curve2(x,y,idn);
  break;
case 3:
    new enigma::OBJ_sprCurve3(x,y,idn);
  break;
case 4:
    new enigma::OBJ_Curve4(x,y,idn);
  break;
case 5:
    new enigma::OBJ_RoofCurve(x,y,idn);
  break;
case 6:
    new enigma::OBJ_Player(x,y,idn);
  break;
case 7:
    new enigma::OBJ_AngleLeft(x,y,idn);
  break;
case 8:
    new enigma::OBJ_AngleRight(x,y,idn);
  break;
case 9:
    new enigma::OBJ_Credit(x,y,idn);
  break;
case 10:
    new enigma::OBJ_afterimage(x,y,idn);
  break;
case 11:
    new enigma::OBJ_rail2(x,y,idn);
  break;
case 12:
    new enigma::OBJ_spark(x,y,idn);
  break;
case 13:
    new enigma::OBJ_rail3(x,y,idn);
  break;
case 14:
    new enigma::OBJ_rail1(x,y,idn);
  break;
case 15:
    new enigma::OBJ_rail4(x,y,idn);
  break;
case 16:
    new enigma::OBJ_dust(x,y,idn);
  break;
case 17:
    new enigma::OBJ_loopleft(x,y,idn);
  break;
case 18:
    new enigma::OBJ_loopright(x,y,idn);
  break;
case 19:
    new enigma::OBJ_looptop(x,y,idn);
  break;
case 20:
    new enigma::OBJ_loopbottom(x,y,idn);
  break;
case 21:
    new enigma::OBJ_flatfloor(x,y,idn);
  break;
case 22:
    new enigma::OBJ_object22(x,y,idn);
  break;
case 23:
    new enigma::OBJ_object23(x,y,idn);
  break;
case 24:
    new enigma::OBJ_object24(x,y,idn);
  break;
case 25:
    new enigma::OBJ_object25(x,y,idn);
  break;
case 26:
    new enigma::OBJ_flatrail(x,y,idn);
  break;
case 27:
    new enigma::OBJ_downrail(x,y,idn);
  break;
case 28:
    new enigma::OBJ_raildl(x,y,idn);
  break;
case 29:
    new enigma::OBJ_raildr(x,y,idn);
  break;
case 30:
    new enigma::OBJ_object30(x,y,idn);
  break;
case 31:
    new enigma::OBJ_goleft(x,y,idn);
  break;
case 32:
    new enigma::OBJ_object32(x,y,idn);
  break;
case 33:
    new enigma::OBJ_city(x,y,idn);
  break;
case 34:
    new enigma::OBJ_gotop(x,y,idn);
  break;
case 35:
    new enigma::OBJ_train(x,y,idn);
  break;
case 36:
    new enigma::OBJ_ramp(x,y,idn);
  break;
case 37:
    new enigma::OBJ_hud(x,y,idn);
  break;
case 38:
    new enigma::OBJ_object38(x,y,idn);
  break;
case 39:
    new enigma::OBJ_looprailR(x,y,idn);
  break;
case 40:
    new enigma::OBJ_looprailL(x,y,idn);
  break;
case 41:
    new enigma::OBJ_raildownSOLID(x,y,idn);
  break;
case 42:
    new enigma::OBJ_object42(x,y,idn);
  break;
case 43:
    new enigma::OBJ_goright(x,y,idn);
  break;
case 44:
    new enigma::OBJ_gobottom(x,y,idn);
  break;
case 45:
    new enigma::OBJ_railflatSOLID(x,y,idn);
  break;
case 46:
    new enigma::OBJ_xtralife(x,y,idn);
  break;
case 47:
    new enigma::OBJ_canyon(x,y,idn);
  break;
case 48:
    new enigma::OBJ_looprailTL(x,y,idn);
  break;
case 49:
    new enigma::OBJ_looprailTR(x,y,idn);
  break;
case 50:
    new enigma::OBJ_miniSolid(x,y,idn);
  break;
case 51:
    new enigma::OBJ_elevator(x,y,idn);
  break;
case 52:
    new enigma::OBJ_stopper(x,y,idn);
  break;
case 53:
    new enigma::OBJ_elevatoredge(x,y,idn);
  break;
case 54:
    new enigma::OBJ_emerald(x,y,idn);
  break;
case 55:
    new enigma::OBJ_emeralddust(x,y,idn);
  break;
case 56:
    new enigma::OBJ_specialring(x,y,idn);
  break;
case 57:
    new enigma::OBJ_object57(x,y,idn);
  break;
case 58:
    new enigma::OBJ_badsonic(x,y,idn);
  break;
case 59:
    new enigma::OBJ_movingfloor(x,y,idn);
  break;
case 60:
    new enigma::OBJ_wall(x,y,idn);
  break;
case 61:
    new enigma::OBJ_curvetopleft(x,y,idn);
  break;
case 62:
    new enigma::OBJ_object62(x,y,idn);
  break;
case 63:
    new enigma::OBJ_object63(x,y,idn);
  break;
case 64:
    new enigma::OBJ_object64(x,y,idn);
  break;
case 65:
    new enigma::OBJ_object65(x,y,idn);
  break;
case 66:
    new enigma::OBJ_object66(x,y,idn);
  break;
case 67:
    new enigma::OBJ_object67(x,y,idn);
  break;
case 68:
    new enigma::OBJ_object68(x,y,idn);
  break;
case 69:
    new enigma::OBJ_object69(x,y,idn);
  break;
case 70:
    new enigma::OBJ_movie(x,y,idn);
  break;
case 71:
    new enigma::OBJ_Rail_Canyon(x,y,idn);
  break;
case 72:
    new enigma::OBJ_Route_99(x,y,idn);
  break;
case 73:
    new enigma::OBJ_Special___Stage(x,y,idn);
  break;
case 74:
    new enigma::OBJ_intro(x,y,idn);
  break;
case 75:
    new enigma::OBJ_titlescreen(x,y,idn);
  break;
case 76:
    new enigma::OBJ_knuckles(x,y,idn);
  break;
case 77:
    new enigma::OBJ_afterimageknux(x,y,idn);
  break;
case 78:
    new enigma::OBJ_playerpick(x,y,idn);
  break;
case 79:
    new enigma::OBJ_big_79(x,y,idn);
  break;
case 80:
    new enigma::OBJ_big_80(x,y,idn);
  break;
case 81:
    new enigma::OBJ_object81(x,y,idn);
  break;
case 82:
    new enigma::OBJ_object82(x,y,idn);
  break;
case 83:
    new enigma::OBJ_object83(x,y,idn);
  break;
case 84:
    new enigma::OBJ_object84(x,y,idn);
  break;
case 85:
    new enigma::OBJ_object85(x,y,idn);
  break;
case 86:
    new enigma::OBJ_spike_shield(x,y,idn);
  break;
case 87:
    new enigma::OBJ_electricshield(x,y,idn);
  break;
case 88:
    new enigma::OBJ_electric_shield(x,y,idn);
  break;
case 89:
    new enigma::OBJ_object89(x,y,idn);
  break;
case 90:
    new enigma::OBJ_spikeshield(x,y,idn);
  break;
case 91:
    new enigma::OBJ_rocky(x,y,idn);
  break;
case 92:
    new enigma::OBJ_rocky2(x,y,idn);
  break;
case 93:
    new enigma::OBJ_Alaska(x,y,idn);
  break;
case 94:
    new enigma::OBJ_water(x,y,idn);
  break;
case 95:
    new enigma::OBJ_alaska(x,y,idn);
  break;
case 96:
    new enigma::OBJ_elec_96(x,y,idn);
  break;
case 97:
    new enigma::OBJ_fire_shield(x,y,idn);
  break;
case 98:
    new enigma::OBJ_fireshield(x,y,idn);
  break;
case 99:
    new enigma::OBJ_bubbleshield(x,y,idn);
  break;
case 100:
    new enigma::OBJ_bubble_shield_100(x,y,idn);
  break;
case 101:
    new enigma::OBJ_vertfloor(x,y,idn);
  break;
case 102:
    new enigma::OBJ_panel(x,y,idn);
  break;
case 103:
    new enigma::OBJ_fadeout(x,y,idn);
  break;
case 104:
    new enigma::OBJ_plane(x,y,idn);
  break;
case 105:
    new enigma::OBJ_on_ice(x,y,idn);
  break;
case 106:
    new enigma::OBJ_object106(x,y,idn);
  break;
case 107:
    new enigma::OBJ_smoke(x,y,idn);
  break;
case 108:
    new enigma::OBJ_icewall(x,y,idn);
  break;
case 109:
    new enigma::OBJ_snowflake(x,y,idn);
  break;
case 110:
    new enigma::OBJ_skinnyflat(x,y,idn);
  break;
case 111:
    new enigma::OBJ_flat_er(x,y,idn);
  break;
case 112:
    new enigma::OBJ_watersurface(x,y,idn);
  break;
case 113:
    new enigma::OBJ_wlmaker(x,y,idn);
  break;
case 114:
    new enigma::OBJ_eggopening(x,y,idn);
  break;
case 115:
    new enigma::OBJ_eyes(x,y,idn);
  break;
case 116:
    new enigma::OBJ_speachopening(x,y,idn);
  break;
case 117:
    new enigma::OBJ_snowmaker(x,y,idn);
  break;
case 118:
    new enigma::OBJ_solidonlyafter(x,y,idn);
  break;
case 119:
    new enigma::OBJ_solidonlywhengrinding(x,y,idn);
  break;
case 120:
    new enigma::OBJ_curvetopright(x,y,idn);
  break;
case 121:
    new enigma::OBJ_solidonlywhengrindingcurveupleft(x,y,idn);
  break;
case 122:
    new enigma::OBJ_boostpad_U_L(x,y,idn);
  break;
case 123:
    new enigma::OBJ_railbottomhalf(x,y,idn);
  break;
case 124:
    new enigma::OBJ_boost_pad_front(x,y,idn);
  break;
case 125:
    new enigma::OBJ_solidonlyafter_r_d(x,y,idn);
  break;
case 126:
    new enigma::OBJ_top(x,y,idn);
  break;
case 127:
    new enigma::OBJ_stem(x,y,idn);
  break;
case 128:
    new enigma::OBJ_oppeningcredits(x,y,idn);
  break;
case 129:
    new enigma::OBJ_flatrailsolid_if_above(x,y,idn);
  break;
case 130:
    new enigma::OBJ_object130(x,y,idn);
  break;

