/********************************************************************************\
**                                                                              **
**  Copyright (C) 2008 Josh Ventura                                             **
**                                                                              **
**  This file is a part of the ENIGMA Development Environment.                  **
**                                                                              **
**                                                                              **
**  ENIGMA is free software: you can redistribute it and/or modify it under the **
**  terms of the GNU General Public License as published by the Free Software   **
**  Foundation, version 3 of the license or any later version.                  **
**                                                                              **
**  This application and its source code is distributed AS-IS, WITHOUT ANY      **
**  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS   **
**  FOR A PARTICULAR PURPOSE. See the GNU General Public License for more       **
**  details.                                                                    **
**                                                                              **
**  You should have recieved a copy of the GNU General Public License along     **
**  with this code. If not, see <http://www.gnu.org/licenses/>                  **
**                                                                              **
**  ENIGMA is an environment designed to create games and other programs with a **
**  high-level, fully compilable language. Developers of ENIGMA or anything     **
**  associated with ENIGMA are in no way responsible for its users or           **
**  applications created by its users, or damages caused by the environment     **
**  or programs made in the environment.                                        **
**                                                                              **
\********************************************************************************/

//This file was generated by the ENIGMA Development Environment.
//Editing it is a sign of a certain medical condition. We're not sure which one.

case 0:
    new enigma::OBJ_object0(x,y,idn);
  break;
case 1:
    new enigma::OBJ_object1(x,y,idn);
  break;
case 7:
    new enigma::OBJ_object7(x,y,idn);
  break;
case 8:
    new enigma::OBJ_object8(x,y,idn);
  break;
case 9:
    new enigma::OBJ_object9(x,y,idn);
  break;
case 10:
    new enigma::OBJ_object10(x,y,idn);
  break;
case 13:
    new enigma::OBJ_object13(x,y,idn);
  break;
case 14:
    new enigma::OBJ_object14(x,y,idn);
  break;
case 15:
    new enigma::OBJ_object15(x,y,idn);
  break;
case 16:
    new enigma::OBJ_nexroomdelay10(x,y,idn);
  break;
case 17:
    new enigma::OBJ_room3(x,y,idn);
  break;
case 20:
    new enigma::OBJ_object20(x,y,idn);
  break;
case 21:
    new enigma::OBJ_object21(x,y,idn);
  break;
case 22:
    new enigma::OBJ_object22(x,y,idn);
  break;
case 23:
    new enigma::OBJ_object23(x,y,idn);
  break;
case 24:
    new enigma::OBJ_object24(x,y,idn);
  break;
case 25:
    new enigma::OBJ_object25(x,y,idn);
  break;
case 26:
    new enigma::OBJ_delay30(x,y,idn);
  break;
case 27:
    new enigma::OBJ_object27(x,y,idn);
  break;
case 28:
    new enigma::OBJ_object28(x,y,idn);
  break;
case 29:
    new enigma::OBJ_object29(x,y,idn);
  break;
case 30:
    new enigma::OBJ_object30(x,y,idn);
  break;
case 32:
    new enigma::OBJ_object32(x,y,idn);
  break;

