/********************************************************************************\
**                                                                              **
**  Copyright (C) 2008 Josh Ventura                                             **
**                                                                              **
**  This file is a part of the ENIGMA Development Environment.                  **
**                                                                              **
**                                                                              **
**  ENIGMA is free software: you can redistribute it and/or modify it under the **
**  terms of the GNU General Public License as published by the Free Software   **
**  Foundation, version 3 of the license or any later version.                  **
**                                                                              **
**  This application and its source code is distributed AS-IS, WITHOUT ANY      **
**  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS   **
**  FOR A PARTICULAR PURPOSE. See the GNU General Public License for more       **
**  details.                                                                    **
**                                                                              **
**  You should have recieved a copy of the GNU General Public License along     **
**  with this code. If not, see <http://www.gnu.org/licenses/>                  **
**                                                                              **
**  ENIGMA is an environment designed to create games and other programs with a **
**  high-level, fully compilable language. Developers of ENIGMA or anything     **
**  associated with ENIGMA are in no way responsible for its users or           **
**  applications created by its users, or damages caused by the environment     **
**  or programs made in the environment.                                        **
**                                                                              **
\********************************************************************************/

//This file was generated by the ENIGMA Development Environment.
//Editing it is a sign of a certain medical condition. We're not sure which one.

namespace enigma
{
  event_iter *event_alarm; // Defined in 1 objects
  event_iter *event_beginstep; // Defined in 1 objects
  event_iter *event_create; // Defined in 11 objects
  event_iter *event_destroy; // Defined in 9 objects
  event_iter *event_draw; // Defined in 5 objects
  event_iter *event_globalleftpress; // Defined in 1 objects
  event_iter *event_globalrightpress; // Defined in 1 objects
  event_iter *event_keypress; // Defined in 7 objects
  event_iter *event_mousewheeldown; // Defined in 1 objects
  event_iter *event_mousewheelup; // Defined in 1 objects
  event_iter *event_step; // Defined in 10 objects
  int event_system_initialize()
  {
    events = new event_iter[11]; // Allocated here; not really meant to change.
    objects = new objectid_base[128]; // Allocated here; not really meant to change.
    event_alarm = events + 0;  event_alarm->name = "Alarm ...";
    event_beginstep = events + 1;  event_beginstep->name = "Begin Step";
    event_create = events + 2;  event_create->name = "Create";
    event_destroy = events + 3;  event_destroy->name = "Destroy";
    event_draw = events + 4;  event_draw->name = "Draw";
    event_globalleftpress = events + 5;  event_globalleftpress->name = "Global Left Press";
    event_globalrightpress = events + 6;  event_globalrightpress->name = "Global Right Press";
    event_keypress = events + 7;  event_keypress->name = "Press <key39>";
    event_mousewheeldown = events + 8;  event_mousewheeldown->name = "Mouse Wheel Down";
    event_mousewheelup = events + 9;  event_mousewheelup->name = "Mouse Wheel Up";
    event_step = events + 10;  event_step->name = "Step";
    return 0;
  }
  int ENIGMA_events()
  {
    for (instance_event_iterator = event_beginstep->next; instance_event_iterator != NULL; instance_event_iterator = instance_event_iterator->next)
      ((enigma::event_parent*)(instance_event_iterator->inst))->myevent_beginstep();
    
    enigma::update_globals();
    
    for (instance_event_iterator = event_alarm->next; instance_event_iterator != NULL; instance_event_iterator = instance_event_iterator->next)
      ((enigma::event_parent*)(instance_event_iterator->inst))->myevent_alarm();
    
    enigma::update_globals();
    
    for (instance_event_iterator = event_keypress->next; instance_event_iterator != NULL; instance_event_iterator = instance_event_iterator->next)
      ((enigma::event_parent*)(instance_event_iterator->inst))->myevent_keypress();
    
    enigma::update_globals();
    
    if (mouse_vscrolls > 0)
      for (instance_event_iterator = event_mousewheelup->next; instance_event_iterator != NULL; instance_event_iterator = instance_event_iterator->next)
        ((enigma::event_parent*)(instance_event_iterator->inst))->myevent_mousewheelup();
    
    enigma::update_globals();
    
    if (mouse_vscrolls < 0)
      for (instance_event_iterator = event_mousewheeldown->next; instance_event_iterator != NULL; instance_event_iterator = instance_event_iterator->next)
        ((enigma::event_parent*)(instance_event_iterator->inst))->myevent_mousewheeldown();
    
    enigma::update_globals();
    
    if (mouse_check_button_pressed(mb_left))
      for (instance_event_iterator = event_globalleftpress->next; instance_event_iterator != NULL; instance_event_iterator = instance_event_iterator->next)
        ((enigma::event_parent*)(instance_event_iterator->inst))->myevent_globalleftpress();
    
    enigma::update_globals();
    
    if (mouse_check_button_pressed(mb_right))
      for (instance_event_iterator = event_globalrightpress->next; instance_event_iterator != NULL; instance_event_iterator = instance_event_iterator->next)
        ((enigma::event_parent*)(instance_event_iterator->inst))->myevent_globalrightpress();
    
    enigma::update_globals();
    
    for (instance_event_iterator = event_step->next; instance_event_iterator != NULL; instance_event_iterator = instance_event_iterator->next)
      ((enigma::event_parent*)(instance_event_iterator->inst))->myevent_step();
    
    enigma::update_globals();
    
    screen_redraw(); screen_refresh();    
    
    enigma::update_globals();
    
    enigma::dispose_destroyed_instances();
    enigma::sleep_for_framerate(room_speed);
    
    return 0;
  } // event function
} // namespace enigma
