/********************************************************************************\
**                                                                              **
**  Copyright (C) 2008 Josh Ventura                                             **
**                                                                              **
**  This file is a part of the ENIGMA Development Environment.                  **
**                                                                              **
**                                                                              **
**  ENIGMA is free software: you can redistribute it and/or modify it under the **
**  terms of the GNU General Public License as published by the Free Software   **
**  Foundation, version 3 of the license or any later version.                  **
**                                                                              **
**  This application and its source code is distributed AS-IS, WITHOUT ANY      **
**  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS   **
**  FOR A PARTICULAR PURPOSE. See the GNU General Public License for more       **
**  details.                                                                    **
**                                                                              **
**  You should have recieved a copy of the GNU General Public License along     **
**  with this code. If not, see <http://www.gnu.org/licenses/>                  **
**                                                                              **
**  ENIGMA is an environment designed to create games and other programs with a **
**  high-level, fully compilable language. Developers of ENIGMA or anything     **
**  associated with ENIGMA are in no way responsible for its users or           **
**  applications created by its users, or damages caused by the environment     **
**  or programs made in the environment.                                        **
**                                                                              **
\********************************************************************************/

//This file was generated by the ENIGMA Development Environment.
//Editing it is a sign of a certain medical condition. We're not sure which one.

namespace enigma {
  int room_loadtimecount = 2;
  roomstruct grd_rooms[2] = {
    //Room 40
    { 40, "Tile_Screen",  "Tile Screen",
      0, roomcreate40,
      1280, 448, 30,  true, {
      { -1,   0, 0, 512, 448,   0, 0, 768, 672,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
}, {      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false },
      },      2,       (enigma::inst*)(int[]){199896,163,640,0,199897,161,144,288,  0,0,0,0}
    },
    //Room 9
    { 9, "base1",  "Base",
      0xc0c0c0, roomcreate9,
      512, 480, 60,  true, {
      { -1,   0, 0, 512, 480,   0, 0, 768, 672,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
}, {      { true,   false,   43,   0,   0,   0,   0,   false,   false,   false },
      { false,   false,   44,   0,   0,   0,   0,   true,   true,   false },
      { false,   false,   45,   0,   0,   0,   0,   true,   true,   false },
      { false,   false,   46,   0,   0,   0,   0,   true,   true,   false },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false },
      },      4,       (enigma::inst*)(int[]){199918,164,80,288,199919,164,80,320,199932,57,264,376,200026,-1,224,176,  0,0,0,0}
    },
  };
  
  int room_max = 40 + 1;
  int maxid = 200026 + 1;
} // Namespace enigma
