/********************************************************************************\
**                                                                              **
**  Copyright (C) 2008 Josh Ventura                                             **
**                                                                              **
**  This file is a part of the ENIGMA Development Environment.                  **
**                                                                              **
**                                                                              **
**  ENIGMA is free software: you can redistribute it and/or modify it under the **
**  terms of the GNU General Public License as published by the Free Software   **
**  Foundation, version 3 of the license or any later version.                  **
**                                                                              **
**  This application and its source code is distributed AS-IS, WITHOUT ANY      **
**  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS   **
**  FOR A PARTICULAR PURPOSE. See the GNU General Public License for more       **
**  details.                                                                    **
**                                                                              **
**  You should have recieved a copy of the GNU General Public License along     **
**  with this code. If not, see <http://www.gnu.org/licenses/>                  **
**                                                                              **
**  ENIGMA is an environment designed to create games and other programs with a **
**  high-level, fully compilable language. Developers of ENIGMA or anything     **
**  associated with ENIGMA are in no way responsible for its users or           **
**  applications created by its users, or damages caused by the environment     **
**  or programs made in the environment.                                        **
**                                                                              **
\********************************************************************************/

//This file was generated by the ENIGMA Development Environment.
//Editing it is a sign of a certain medical condition. We're not sure which one.

namespace enigma {
  int room_loadtimecount = 9;
  roomstruct grd_rooms[9] = {
    //Room 2
    { 2, "room2",  "",
      0, roomcreate2,
      320, 240, 30,  true, {
      { -1,   0, 0, 320, 240,   0, 0, 320, 240,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
}, {      { false,   false,   3,   0,   0,   0,   0,   true,   true,   false },
      { false,   false,   1,   0,   0,   0,   1,   true,   true,   false },
      { false,   false,   -1,   0,   0,   -1,   -1,   true,   true,   false },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false },
      },      11,       (enigma::inst*)(int[]){100196,13,157,71,100198,9,30,7,100199,9,9,25,100200,9,1,51,100201,9,276,6,100204,9,303,20,100206,9,312,43,100207,9,11,9,100208,9,295,7,100209,9,71,140,100210,9,233,142,  0,0,0,0}
    },
    //Room 0
    { 0, "room0",  "",
      0, roomcreate0,
      320, 240, 30,  true, {
      { -1,   0, 0, 320, 240,   0, 0, 320, 240,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
}, {      { true,   false,   3,   0,   0,   0,   0,   true,   true,   false },
      { false,   false,   1,   0,   0,   0,   1,   true,   true,   false },
      { false,   false,   -1,   0,   0,   -1,   -1,   true,   true,   false },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false },
      },      21,       (enigma::inst*)(int[]){100093,7,0,0,100095,0,161,50,100096,1,158,48,100098,1,155,46,100212,16,166,177,100159,14,83,67,100160,14,71,53,100161,14,67,26,100162,14,73,4,100163,14,226,66,100164,14,235,50,100165,14,236,22,100166,14,226,2,100167,14,284,31,100168,14,28,32,100169,14,74,127,
        100170,14,154,136,100171,14,245,127,100172,14,2,2,100173,14,313,1,100158,15,156,91,  0,0,0,0}
    },
    //Room 4
    { 4, "room4",  "",
      0, roomcreate4,
      320, 240, 30,  true, {
      { -1,   0, 0, 320, 240,   0, 0, 320, 240,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
}, {      { true,   false,   4,   0,   0,   0,   0,   true,   true,   false },
      { false,   false,   1,   0,   0,   0,   1,   true,   true,   false },
      { false,   false,   -1,   0,   0,   -1,   -1,   true,   true,   false },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false },
      },      3,       (enigma::inst*)(int[]){100213,17,108,93,100214,16,194,137,100217,20,217,4,  0,0,0,0}
    },
    //Room 5
    { 5, "room5",  "",
      0, roomcreate5,
      320, 240, 30,  true, {
      { -1,   0, 0, 320, 240,   0, 0, 320, 240,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
}, {      { true,   false,   5,   0,   0,   0,   0,   true,   true,   false },
      { false,   false,   1,   0,   0,   0,   1,   true,   true,   false },
      { false,   false,   -1,   0,   0,   -1,   -1,   true,   true,   false },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false },
      },      2,       (enigma::inst*)(int[]){100214,16,194,137,100223,21,1,188,  0,0,0,0}
    },
    //Room 3
    { 3, "room_room3_3",  "",
      0, roomcreate3,
      320, 240, 30,  true, {
      { -1,   0, 0, 320, 240,   0, 0, 320, 240,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
}, {      { true,   false,   6,   0,   0,   0,   0,   true,   true,   false },
      { false,   false,   1,   0,   0,   0,   1,   true,   true,   false },
      { false,   false,   -1,   0,   0,   -1,   -1,   true,   true,   false },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false },
      },      3,       (enigma::inst*)(int[]){100227,16,185,164,100244,22,0,0,100246,23,56,48,  0,0,0,0}
    },
    //Room 6
    { 6, "room6",  "",
      0, roomcreate6,
      320, 240, 30,  true, {
      { -1,   0, 0, 320, 240,   0, 0, 320, 240,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
}, {      { true,   false,   7,   0,   0,   0,   0,   true,   true,   false },
      { false,   false,   1,   0,   0,   0,   1,   true,   true,   false },
      { false,   false,   -1,   0,   0,   -1,   -1,   true,   true,   false },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false },
      },      3,       (enigma::inst*)(int[]){100231,24,0,113,100233,25,197,190,100234,26,192,78,  0,0,0,0}
    },
    //Room 7
    { 7, "room7",  "",
      0, roomcreate7,
      320, 240, 30,  true, {
      { -1,   0, 0, 320, 240,   0, 0, 320, 240,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
}, {      { true,   false,   8,   0,   0,   0,   0,   true,   true,   false },
      { false,   false,   1,   0,   0,   0,   1,   true,   true,   false },
      { false,   false,   -1,   0,   0,   -1,   -1,   true,   true,   false },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false },
      },      3,       (enigma::inst*)(int[]){100236,16,159,128,100237,27,218,98,100238,28,111,190,  0,0,0,0}
    },
    //Room 8
    { 8, "room8",  "",
      0, roomcreate8,
      320, 240, 30,  true, {
      { -1,   0, 0, 320, 240,   0, 0, 320, 240,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
}, {      { true,   false,   8,   0,   0,   0,   0,   true,   true,   false },
      { false,   false,   1,   0,   0,   0,   1,   true,   true,   false },
      { false,   false,   -1,   0,   0,   -1,   -1,   true,   true,   false },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false },
      },      2,       (enigma::inst*)(int[]){100239,29,125,151,100240,16,131,123,  0,0,0,0}
    },
    //Room 9
    { 9, "room9",  "",
      0, roomcreate9,
      320, 240, 30,  true, {
      { -1,   0, 0, 320, 240,   0, 0, 320, 240,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
}, {      { true,   false,   3,   0,   0,   0,   0,   true,   true,   false },
      { false,   false,   1,   0,   0,   0,   1,   true,   true,   false },
      { false,   false,   -1,   0,   0,   -1,   -1,   true,   true,   false },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false },
      },      2,       (enigma::inst*)(int[]){100251,32,0,0,100241,30,74,67,  0,0,0,0}
    },
  };
  
  int room_max = 9 + 1;
  int maxid = 100251 + 1;
} // Namespace enigma
