/********************************************************************************\
**                                                                              **
**  Copyright (C) 2008 Josh Ventura                                             **
**                                                                              **
**  This file is a part of the ENIGMA Development Environment.                  **
**                                                                              **
**                                                                              **
**  ENIGMA is free software: you can redistribute it and/or modify it under the **
**  terms of the GNU General Public License as published by the Free Software   **
**  Foundation, version 3 of the license or any later version.                  **
**                                                                              **
**  This application and its source code is distributed AS-IS, WITHOUT ANY      **
**  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS   **
**  FOR A PARTICULAR PURPOSE. See the GNU General Public License for more       **
**  details.                                                                    **
**                                                                              **
**  You should have recieved a copy of the GNU General Public License along     **
**  with this code. If not, see <http://www.gnu.org/licenses/>                  **
**                                                                              **
**  ENIGMA is an environment designed to create games and other programs with a **
**  high-level, fully compilable language. Developers of ENIGMA or anything     **
**  associated with ENIGMA are in no way responsible for its users or           **
**  applications created by its users, or damages caused by the environment     **
**  or programs made in the environment.                                        **
**                                                                              **
\********************************************************************************/

//This file was generated by the ENIGMA Development Environment.
//Editing it is a sign of a certain medical condition. We're not sure which one.

namespace enigma {
  int room_loadtimecount = 11;
  roomstruct grd_rooms[11] = {
    //Room 1
    { 1, "Maenigmainmenu",  "",
      0x30006, roomcreate1,
      640, 480, 60,  false, {
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
}, {      { true,   false,   12,   0,   -150,   0,   0,   false,   false,   false },
      { true,   false,   14,   0,   0,   1,   0,   true,   true,   false },
      { true,   false,   10,   50,   50,   1,   6,   true,   true,   false },
      { true,   false,   15,   110,   0,   0,   0,   false,   false,   false },
      { true,   false,   4,   350,   225,   6,   0,   true,   false,   false },
      { true,   false,   4,   0,   235,   12,   0,   true,   false,   false },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false },
      },      6,       (enigma::inst*)(int[]){100300,185,16,256,100413,24,448,320,100420,231,448,352,100429,23,448,384,100436,232,440,416,100320,100,128,192,  0,0,0,0}
    },
    //Room 15
    { 15, "startenigmaingenigmanewgameroom",  "",
      0x30006, roomcreate15,
      640, 480, 60,  false, {
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
}, {      { true,   false,   12,   0,   -150,   0,   0,   false,   false,   false },
      { true,   false,   14,   0,   0,   1,   0,   true,   true,   false },
      { true,   false,   10,   50,   50,   1,   6,   true,   true,   false },
      { true,   false,   15,   110,   0,   0,   0,   false,   false,   false },
      { true,   false,   4,   350,   225,   6,   0,   true,   false,   false },
      { true,   false,   4,   0,   235,   12,   0,   true,   false,   false },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false },
      },      2,       (enigma::inst*)(int[]){100729,359,16,448,100320,100,128,160,  0,0,0,0}
    },
    //Room 0
    { 0, "earthmaenigmainroom",  "",
      0x51, roomcreate0,
      640, 480, 60,  false, {
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
}, {      { true,   false,   2,   0,   -75,   0,   0,   true,   true,   false },
      { true,   false,   3,   0,   0,   -1,   -1,   true,   true,   false },
      { true,   false,   0,   0,   0,   0,   0,   true,   true,   false },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false },
      },      26,       (enigma::inst*)(int[]){100022,1,400,16,100024,2,448,16,100045,4,496,16,100048,7,496,64,100049,5,544,64,100131,6,592,64,100132,3,592,16,100133,8,544,16,100134,0,352,16,100167,12,544,112,100176,37,500,440,100183,44,304,288,100193,54,48,224,100206,76,48,0,100214,79,80,0,100216,25,0,0,
        100245,112,592,112,100107,17,0,460,100194,64,0,16,100116,19,600,440,100117,20,560,440,100112,18,520,440,100179,41,0,448,100180,42,608,448,100195,43,208,448,100236,100,32,32,  0,0,0,0}
    },
    //Room 6
    { 6, "checklist",  "",
      0x30006, roomcreate6,
      640, 480, 60,  false, {
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
}, {      { true,   false,   12,   0,   -150,   0,   0,   false,   false,   false },
      { true,   false,   14,   0,   0,   1,   0,   true,   true,   false },
      { true,   false,   10,   50,   50,   1,   6,   true,   true,   false },
      { true,   false,   15,   110,   0,   0,   0,   false,   false,   false },
      { true,   false,   4,   350,   225,   6,   0,   true,   false,   false },
      { true,   false,   4,   0,   235,   12,   0,   true,   false,   false },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false },
      },      11,       (enigma::inst*)(int[]){100378,225,0,32,100398,226,452,4,100684,350,208,408,100694,352,512,448,100705,227,40,64,100706,224,0,160,100708,229,40,192,100714,223,0,288,100718,230,40,320,100728,358,112,248,100320,100,128,192,  0,0,0,0}
    },
    //Room 7
    { 7, "theMuseum",  "",
      0x30006, roomcreate7,
      640, 480, 60,  false, {
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
}, {      { true,   false,   12,   0,   -150,   0,   0,   false,   false,   false },
      { true,   false,   14,   0,   0,   1,   0,   true,   true,   false },
      { true,   false,   10,   50,   50,   1,   6,   true,   true,   false },
      { true,   false,   15,   110,   0,   0,   0,   false,   false,   false },
      { true,   false,   4,   350,   225,   6,   0,   true,   false,   false },
      { true,   false,   4,   0,   235,   12,   0,   true,   false,   false },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false },
      },      9,       (enigma::inst*)(int[]){100506,264,8,0,100518,269,24,256,100524,265,24,168,100526,267,352,168,100529,268,352,256,100533,270,184,88,100537,266,192,336,100560,278,584,424,100320,100,128,160,  0,0,0,0}
    },
    //Room 8
    { 8, "theroryroom",  "",
      0x30006, roomcreate8,
      640, 480, 60,  false, {
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
}, {      { true,   false,   12,   0,   -150,   0,   0,   false,   false,   false },
      { true,   false,   14,   0,   0,   1,   0,   true,   true,   false },
      { true,   false,   10,   50,   50,   1,   6,   true,   true,   false },
      { true,   false,   15,   110,   0,   0,   0,   false,   false,   false },
      { true,   false,   4,   350,   225,   6,   0,   true,   false,   false },
      { true,   false,   4,   0,   235,   12,   0,   true,   false,   false },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false },
      },      4,       (enigma::inst*)(int[]){100506,264,8,0,100510,272,584,424,100549,273,16,80,100320,100,128,160,  0,0,0,0}
    },
    //Room 12
    { 12, "worksroom",  "",
      0x30006, roomcreate12,
      640, 480, 60,  false, {
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
}, {      { true,   false,   12,   0,   -150,   0,   0,   false,   false,   false },
      { true,   false,   14,   0,   0,   1,   0,   true,   true,   false },
      { true,   false,   10,   50,   50,   1,   6,   true,   true,   false },
      { true,   false,   15,   110,   0,   0,   0,   false,   false,   false },
      { true,   false,   4,   350,   225,   6,   0,   true,   false,   false },
      { true,   false,   4,   0,   235,   12,   0,   true,   false,   false },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false },
      },      4,       (enigma::inst*)(int[]){100506,264,8,0,100510,272,584,424,100588,287,16,120,100320,100,128,160,  0,0,0,0}
    },
    //Room 13
    { 13, "creditsroom",  "",
      0x30006, roomcreate13,
      640, 480, 60,  false, {
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
}, {      { true,   false,   12,   0,   -150,   0,   0,   false,   false,   false },
      { true,   false,   14,   0,   0,   1,   0,   true,   true,   false },
      { true,   false,   10,   50,   50,   1,   6,   true,   true,   false },
      { true,   false,   15,   110,   0,   0,   0,   false,   false,   false },
      { true,   false,   4,   350,   225,   6,   0,   true,   false,   false },
      { true,   false,   4,   0,   235,   12,   0,   true,   false,   false },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false },
      },      4,       (enigma::inst*)(int[]){100591,278,584,424,100605,289,304,80,100606,290,16,256,100320,100,128,160,  0,0,0,0}
    },
    //Room 9
    { 9, "musicroom",  "",
      0x30006, roomcreate9,
      640, 480, 60,  false, {
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
}, {      { true,   false,   12,   0,   -150,   0,   0,   false,   false,   false },
      { true,   false,   14,   0,   0,   1,   0,   true,   true,   false },
      { true,   false,   10,   50,   50,   1,   6,   true,   true,   false },
      { true,   false,   15,   110,   0,   0,   0,   false,   false,   false },
      { true,   false,   4,   350,   225,   6,   0,   true,   false,   false },
      { true,   false,   4,   0,   235,   12,   0,   true,   false,   false },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false },
      },      4,       (enigma::inst*)(int[]){100506,264,8,0,100510,272,584,424,100551,274,48,160,100320,100,128,160,  0,0,0,0}
    },
    //Room 10
    { 10, "enigmainspireroom",  "",
      0x30006, roomcreate10,
      640, 480, 60,  false, {
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
}, {      { true,   false,   12,   0,   -150,   0,   0,   false,   false,   false },
      { true,   false,   14,   0,   0,   1,   0,   true,   true,   false },
      { true,   false,   10,   50,   50,   1,   6,   true,   true,   false },
      { true,   false,   15,   110,   0,   0,   0,   false,   false,   false },
      { true,   false,   4,   350,   225,   6,   0,   true,   false,   false },
      { true,   false,   4,   0,   235,   12,   0,   true,   false,   false },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false },
      },      5,       (enigma::inst*)(int[]){100506,264,8,0,100510,272,584,424,100554,275,16,128,100579,280,248,256,100320,100,128,160,  0,0,0,0}
    },
    //Room 11
    { 11, "vertigoroom",  "",
      0x30006, roomcreate11,
      640, 480, 60,  false, {
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
      { 0,   0, 0, 640, 480,   0, 0, 640, 480,   -1,   32, 32,   -1, -1 },
}, {      { true,   false,   12,   0,   -150,   0,   0,   false,   false,   false },
      { true,   false,   14,   0,   0,   1,   0,   true,   true,   false },
      { true,   false,   10,   50,   50,   1,   6,   true,   true,   false },
      { true,   false,   15,   110,   0,   0,   0,   false,   false,   false },
      { true,   false,   4,   350,   225,   6,   0,   true,   false,   false },
      { true,   false,   4,   0,   235,   12,   0,   true,   false,   false },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false },
      { false,   false,   -1,   0,   0,   0,   0,   true,   true,   false },
      },      5,       (enigma::inst*)(int[]){100506,264,8,0,100510,272,584,424,100555,277,16,128,100581,281,224,272,100320,100,128,160,  0,0,0,0}
    },
  };
  
  int room_max = 15 + 1;
  int maxid = 100729 + 1;
} // Namespace enigma
