/********************************************************************************\
**                                                                              **
**  Copyright (C) 2008 Josh Ventura                                             **
**                                                                              **
**  This file is a part of the ENIGMA Development Environment.                  **
**                                                                              **
**                                                                              **
**  ENIGMA is free software: you can redistribute it and/or modify it under the **
**  terms of the GNU General Public License as published by the Free Software   **
**  Foundation, version 3 of the license or any later version.                  **
**                                                                              **
**  This application and its source code is distributed AS-IS, WITHOUT ANY      **
**  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS   **
**  FOR A PARTICULAR PURPOSE. See the GNU General Public License for more       **
**  details.                                                                    **
**                                                                              **
**  You should have recieved a copy of the GNU General Public License along     **
**  with this code. If not, see <http://www.gnu.org/licenses/>                  **
**                                                                              **
**  ENIGMA is an environment designed to create games and other programs with a **
**  high-level, fully compilable language. Developers of ENIGMA or anything     **
**  associated with ENIGMA are in no way responsible for its users or           **
**  applications created by its users, or damages caused by the environment     **
**  or programs made in the environment.                                        **
**                                                                              **
\********************************************************************************/

//This file was generated by the ENIGMA Development Environment.
//Editing it is a sign of a certain medical condition. We're not sure which one.

enum //object names
{
  obj_wall = 2,
  obj_bot = 3,
  obj_exit = 4,
  obj_food = 5,
  obj_player = 6,
  obj_feeder = 9,
};

enum //sprite names
{
  spr_wall = 0,
  spr_player = 2,
  spr_exit = 3,
  spr_food = 4,
};
namespace enigma { size_t sprite_idmax = 5; }

enum //background names
{
};
namespace enigma { size_t background_idmax = 0; }

enum //font names
{
  EnigmaDefault = -1,
};
namespace enigma { size_t font_idmax = 0; }

enum //sound names
{
  snd_pew = 1,
};
namespace enigma { size_t sound_idmax = 2; }

enum //room names
{
  maze_1 = 1,
};

