/********************************************************************************\
**                                                                              **
**  Copyright (C) 2008 Josh Ventura                                             **
**                                                                              **
**  This file is a part of the ENIGMA Development Environment.                  **
**                                                                              **
**                                                                              **
**  ENIGMA is free software: you can redistribute it and/or modify it under the **
**  terms of the GNU General Public License as published by the Free Software   **
**  Foundation, version 3 of the license or any later version.                  **
**                                                                              **
**  This application and its source code is distributed AS-IS, WITHOUT ANY      **
**  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS   **
**  FOR A PARTICULAR PURPOSE. See the GNU General Public License for more       **
**  details.                                                                    **
**                                                                              **
**  You should have recieved a copy of the GNU General Public License along     **
**  with this code. If not, see <http://www.gnu.org/licenses/>                  **
**                                                                              **
**  ENIGMA is an environment designed to create games and other programs with a **
**  high-level, fully compilable language. Developers of ENIGMA or anything     **
**  associated with ENIGMA are in no way responsible for its users or           **
**  applications created by its users, or damages caused by the environment     **
**  or programs made in the environment.                                        **
**                                                                              **
\********************************************************************************/

//This file was generated by the ENIGMA Development Environment.
//Editing it is a sign of a certain medical condition. We're not sure which one.

namespace enigma
{
  event_iter *event_alarm; // Defined in 1 objects
  event_iter *event_collision; // Defined in 14 objects
  event_iter *event_create; // Defined in 6 objects
  event_iter *event_destroy; // Defined in 1 objects
  event_iter *event_draw; // Defined in 2 objects
  event_iter *event_gamestart; // Defined in 1 objects
  event_iter *event_keyboard; // Defined in 6 objects
  event_iter *event_nomorelives; // Defined in 1 objects
  event_iter *event_outsideroom; // Defined in 5 objects
  event_iter *event_step; // Defined in 4 objects
  int event_system_initialize()
  {
    events = new event_iter[10]; // Allocated here; not really meant to change.
    objects = new objectid_base[7]; // Allocated here; not really meant to change.
    event_alarm = events + 0;  event_alarm->name = "Alarm ...";
    event_collision = events + 1;  event_collision->name = "obj_0";
    event_create = events + 2;  event_create->name = "Create";
    event_destroy = events + 3;  event_destroy->name = "Destroy";
    event_draw = events + 4;  event_draw->name = "Draw";
    event_gamestart = events + 5;  event_gamestart->name = "Game Start";
    event_keyboard = events + 6;  event_keyboard->name = "Keyboard <key1>";
    event_nomorelives = events + 7;  event_nomorelives->name = "No More Lives";
    event_outsideroom = events + 8;  event_outsideroom->name = "Outside Room";
    event_step = events + 9;  event_step->name = "Step";
    return 0;
  }
  int ENIGMA_events()
  {
    for (instance_event_iterator = event_alarm->next; instance_event_iterator != NULL; instance_event_iterator = instance_event_iterator->next)
      ((enigma::event_parent*)(instance_event_iterator->inst))->myevent_alarm();
    
    enigma::update_globals();
    
    for (instance_event_iterator = event_keyboard->next; instance_event_iterator != NULL; instance_event_iterator = instance_event_iterator->next)
      ((enigma::event_parent*)(instance_event_iterator->inst))->myevent_keyboard();
    
    enigma::update_globals();
    
    for (instance_event_iterator = event_step->next; instance_event_iterator != NULL; instance_event_iterator = instance_event_iterator->next)
      ((enigma::event_parent*)(instance_event_iterator->inst))->myevent_step();
    
    enigma::update_globals();
    
    for (instance_event_iterator = event_outsideroom->next; instance_event_iterator != NULL; instance_event_iterator = instance_event_iterator->next)
      ((enigma::event_parent*)(instance_event_iterator->inst))->myevent_outsideroom();
    
    enigma::update_globals();
    
    for (instance_event_iterator = event_collision->next; instance_event_iterator != NULL; instance_event_iterator = instance_event_iterator->next)
      ((enigma::event_parent*)(instance_event_iterator->inst))->myevent_collision();
    
    enigma::update_globals();
    
    for (instance_event_iterator = event_nomorelives->next; instance_event_iterator != NULL; instance_event_iterator = instance_event_iterator->next)
      ((enigma::event_parent*)(instance_event_iterator->inst))->myevent_nomorelives();
    
    enigma::update_globals();
    
    screen_redraw(); screen_refresh();    
    
    enigma::update_globals();
    
    enigma::dispose_destroyed_instances();
    enigma::sleep_for_framerate(room_speed);
    
    return 0;
  } // event function
} // namespace enigma
