/********************************************************************************\
**                                                                              **
**  Copyright (C) 2008 Josh Ventura                                             **
**                                                                              **
**  This file is a part of the ENIGMA Development Environment.                  **
**                                                                              **
**                                                                              **
**  ENIGMA is free software: you can redistribute it and/or modify it under the **
**  terms of the GNU General Public License as published by the Free Software   **
**  Foundation, version 3 of the license or any later version.                  **
**                                                                              **
**  This application and its source code is distributed AS-IS, WITHOUT ANY      **
**  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS   **
**  FOR A PARTICULAR PURPOSE. See the GNU General Public License for more       **
**  details.                                                                    **
**                                                                              **
**  You should have recieved a copy of the GNU General Public License along     **
**  with this code. If not, see <http://www.gnu.org/licenses/>                  **
**                                                                              **
**  ENIGMA is an environment designed to create games and other programs with a **
**  high-level, fully compilable language. Developers of ENIGMA or anything     **
**  associated with ENIGMA are in no way responsible for its users or           **
**  applications created by its users, or damages caused by the environment     **
**  or programs made in the environment.                                        **
**                                                                              **
\********************************************************************************/

//This file was generated by the ENIGMA Development Environment.
//Editing it is a sign of a certain medical condition. We're not sure which one.

void roomcreate1()
{
  ;
  
}
void roomcreate3()
{
  ;
  
}
void roomcreate8()
{
  ;
  
}
void roomcreate0()
{
  ;
  
}
void roomcreate7()
{
  enigma::varaccess_bonus(int(city))= 0;
  enigma::varaccess_bonus(int(Player))= 0;
  enigma::varaccess_bonus(int(movingfloor))= 0;
  enigma::varaccess_wl(int(global))= 384;
  
}
void roomcreate4()
{
  enigma::varaccess_act(int(global))= 0;
  enigma::varaccess_wl(int(global))= room_height;
  
}
void roomcreate2()
{
  enigma::varaccess_act(int(global))= 1;
  enigma::varaccess_wl(int(global))= room_height;
  
}
void roomcreate5()
{
  enigma::varaccess_act(int(global))= 0;
  enigma::varaccess_wl(int(global))= room_height;
  
}
void roomcreate6()
{
  enigma::varaccess_bonus(int(city))=- 12;
  enigma::varaccess_bonus(int(global))= 1;
  enigma::varaccess_bonus(int(movingfloor))=- 12;
  enigma::varaccess_wl(int(global))= room_height;
  
}
void roomcreate9()
{
  enigma::varaccess_act(int(global))= 0;
  enigma::varaccess_wl(int(global))= room_height;
  enigma::varaccess_bonus(int(city))= 0;
  enigma::varaccess_bonus(int(Player))= 0;
  enigma::varaccess_bonus(int(movingfloor))= 0;
  
}
