/********************************************************************************\
**                                                                              **
**  Copyright (C) 2008 Josh Ventura                                             **
**                                                                              **
**  This file is a part of the ENIGMA Development Environment.                  **
**                                                                              **
**                                                                              **
**  ENIGMA is free software: you can redistribute it and/or modify it under the **
**  terms of the GNU General Public License as published by the Free Software   **
**  Foundation, version 3 of the license or any later version.                  **
**                                                                              **
**  This application and its source code is distributed AS-IS, WITHOUT ANY      **
**  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS   **
**  FOR A PARTICULAR PURPOSE. See the GNU General Public License for more       **
**  details.                                                                    **
**                                                                              **
**  You should have recieved a copy of the GNU General Public License along     **
**  with this code. If not, see <http://www.gnu.org/licenses/>                  **
**                                                                              **
**  ENIGMA is an environment designed to create games and other programs with a **
**  high-level, fully compilable language. Developers of ENIGMA or anything     **
**  associated with ENIGMA are in no way responsible for its users or           **
**  applications created by its users, or damages caused by the environment     **
**  or programs made in the environment.                                        **
**                                                                              **
\********************************************************************************/

//This file was generated by the ENIGMA Development Environment.
//Editing it is a sign of a certain medical condition. We're not sure which one.


namespace enigma
{
  struct ENIGMA_global_structure: object_locals
  {
    var CKNomountain;
    var CKThebunnydeath;
    var CKTheforests;
    var CKThegold;
    var CKTheplagues;
    var CKThesilver;
    var CKThetreecity;
    var advancedcitycheck;
    var areallbuttonsgone;
    var bunniesbcdeathcheck;
    var canyoncheck;
    var castlecheck;
    var checkmarkpercentage;
    var comettomountain;
    var cratorcheck;
    var defensecheck;
    var farmcheck;
    var farmgrowthcheck;
    var forest5check;
    var forestcheck;
    var fs_bold;
    var fuelfactorycheck;
    var goldcheck;
    var hasitrainedyet;
    var humaniq100check;
    var humaniq150check;
    var humaniq320check;
    var humansFIGUREitout;
    var icylakecheck;
    var isthefuelthere;
    var istheoilthere;
    var itsnowacavehome;
    var lakecheck;
    var lakefishcheck;
    var lightthevillage;
    var mannowhasahomenow;
    var mountaincheck;
    var nomoreenderamessages;
    var nomountaincheck;
    var notreescheck;
    var nowatercheck;
    var nuclearcheck;
    var oilderrickcheck;
    var peacetreatycheck;
    var plaguesdefendcheck;
    var rabbitIQcountdown;
    var rabbitiq100check;
    var rabbitiq200check;
    var rabbitiq30check;
    var rabbitsaddeathcheck;
    var rank10check;
    var rank1check;
    var rank4check;
    var rank6check;
    var rankofgod;
    var rivercheck;
    var rockcitycheck;
    var rockolawscheck;
    var score8500check;
    var seedlingseatencheck;
    var silvercheck;
    var thehumaniq;
    var therabbitiq;
    var theroundsofgod;
    var treecity2check;
    var treecitycheck;
    var treevariable;
    var villagecheck;
    var volcanocheck;
    var volcanocitycheck;
    var whenbluescoregoes;
    ENIGMA_global_structure(const int x, const int y): object_locals(x,y) {}
  };
  object_basic *ENIGMA_global_instance = new ENIGMA_global_structure(global,global);
}
