/********************************************************************************\
**                                                                              **
**  Copyright (C) 2008 Josh Ventura                                             **
**                                                                              **
**  This file is a part of the ENIGMA Development Environment.                  **
**                                                                              **
**                                                                              **
**  ENIGMA is free software: you can redistribute it and/or modify it under the **
**  terms of the GNU General Public License as published by the Free Software   **
**  Foundation, version 3 of the license or any later version.                  **
**                                                                              **
**  This application and its source code is distributed AS-IS, WITHOUT ANY      **
**  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS   **
**  FOR A PARTICULAR PURPOSE. See the GNU General Public License for more       **
**  details.                                                                    **
**                                                                              **
**  You should have recieved a copy of the GNU General Public License along     **
**  with this code. If not, see <http://www.gnu.org/licenses/>                  **
**                                                                              **
**  ENIGMA is an environment designed to create games and other programs with a **
**  high-level, fully compilable language. Developers of ENIGMA or anything     **
**  associated with ENIGMA are in no way responsible for its users or           **
**  applications created by its users, or damages caused by the environment     **
**  or programs made in the environment.                                        **
**                                                                              **
\********************************************************************************/

//This file was generated by the ENIGMA Development Environment.
//Editing it is a sign of a certain medical condition. We're not sure which one.

enum //object names
{
  obj_player = 0,
  bullit = 30,
  roomname = 44,
  nolook = 48,
  gun_thenigmaing = 53,
  fountaenigmain = 60,
  chunk_obj = 61,
  chunk2_obj = 62,
  gore_spr = 64,
  gore_puddle = 68,
  slpat = 69,
  chunk3 = 70,
  gore_test = 72,
  gore_fountaenigmain_last = 73,
  wallH = 74,
  wallv = 75,
  wallV_basic = 76,
  wall_Hbasic = 77,
  gore_splat = 78,
  wall_basic = 79,
};

enum //sprite names
{
  spr_player = 0,
  sprite1 = 1,
  sprite2 = 2,
  wall2s = 3,
  sprite4 = 4,
  sprite5 = 5,
  sprite6 = 6,
  floor_spr = 7,
  sprite8 = 8,
  sprite9 = 9,
  sprite11 = 11,
  pool = 12,
  sprite14 = 14,
  sprite15 = 15,
  splash_spr = 16,
  targetspr = 18,
  poenigmaenigmainter = 21,
  sprite23 = 23,
  guntex = 25,
  poenigmaenigmainttrans = 26,
  sprite27 = 27,
  sprite28 = 28,
  sprite29 = 29,
  fountaenigmain_spr = 31,
  gore = 32,
  blood_puddle = 33,
  sprite34 = 34,
  sprite35 = 35,
  dummy = 36,
  sprite37 = 37,
};
namespace enigma { size_t sprite_idmax = 38; }

enum //background names
{
  back1 = 0,
  back = 1,
  treetop = 2,
  treebark = 3,
  box = 4,
  chunktex = 13,
};
namespace enigma { size_t background_idmax = 14; }

enum //font names
{
  EnigmaDefault = -1,
  enigenigmamapause_font = 0,
};
namespace enigma { size_t font_idmax = 1; }

enum //timeline names
{
};
namespace enigma { size_t timeline_idmax = 0; }

enum //path names
{
};
namespace enigma { size_t path_idmax = 0; }

enum //sound names
{
  sound2 = 2,
};
namespace enigma { size_t sound_idmax = 3; }

enum //room names
{
  room0 = 0,
};

